apiVersion: v1
kind: ConfigMap
metadata:
  name: assets-configmap
  namespace: {{.Release.Namespace}}
data:
{{- range $path, $_ := .Files.Glob "manifests/dev-plugin/*" }}
{{ printf "%s" (base $path) | indent 2 }}: |-
{{ $.Files.Get $path | indent 4 }}
{{- end }}

{{- range $path, $_ := .Files.Glob "manifests/drv-daemon/*" }}
{{ printf "%s" (base $path) | indent 2 }}: |-
{{ $.Files.Get $path | indent 4 }}
{{- end }}

{{- range $path, $_ := .Files.Glob "manifests/dev-control/*" }}
{{ printf "%s" (base $path) | indent 2 }}: |-
{{ $.Files.Get $path | indent 4 }}
{{- end }}

{{- range $path, $_ := .Files.Glob "manifests/dev-update/*" }}
{{ printf "%s" (base $path) | indent 2 }}: |-
{{ $.Files.Get $path | indent 4 }}
{{- end }}
