apiVersion: acclr.github.com/v1beta1
kind: OctNic
metadata:
  name: generic
  # namespace: {{.Release.Namespace}}
  namespace: default
spec:
  acclr: "f105o"
  fwimage: "registry.local:9001/staging/marvellocteon/docker_fwimage"
  fwtag: "SDK11.23.04"
  nodename: "controller-0"
  pciAddr: "0000:af:00.0"
  numvfs: "7"
  resourcePrefix: "marvell.com"
  resourceName:
    - "marvell_sriov_net_vamp#0-3,octeon_ep_vf"
    - "marvell_sriov_net_rmp#4,5-6,Octeon_ep_vf"

   # - "marvell_sriov_net_vamp#0,vfio-pci"
   # - "marvell_sriov_net_rmp#8-15"
   # - "marvell_sriov_net_dip#20-21"
   # - "marvell_sriov_net_dpp#32,36-37,40-47"
   #fwimage: "marvellocteon/docker_fwimage"
