apiVersion: v1
kind: ServiceAccount
metadata:
  name: oct-sriov-device-plugin
  namespace: {{.Release.Namespace}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: octnic
    app.kubernetes.io/instance: controller-manager
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: serviceaccount
    app.kubernetes.io/part-of: octnic
  name: octnic-controller-manager
  namespace: {{.Release.Namespace}}

