# permissions for end users to view octnics.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: octnic-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: octnic
    app.kubernetes.io/part-of: octnic
    app.kubernetes.io/managed-by: kustomize
  name: octnic-viewer-role
rules:
- apiGroups:
  - acclr.github.com
  resources:
  - octnics
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - acclr.github.com
  resources:
  - octnics/status
  verbs:
  - get
